CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(25) UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE chat (
    id VARCHAR(255) NOT NULL UNIQUE,
    summary_title VARCHAR(255) NOT NULL,
    owner INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    FOREIGN KEY (owner) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE query (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    msg TEXT NOT NULL,
    owner INTEGER NOT NULL,
    chat INTEGER NOT NULL,
    FOREIGN KEY (owner) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (chat) REFERENCES chat(id) ON DELETE CASCADE
);
