CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(255) UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE room (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    summary_title VARCHAR(255) NOT NULL,
    owner INTEGER NOT NULL,
    FOREIGN KEY (owner) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE query (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    owner INTEGER NOT NULL,
    room INTEGER NOT NULL,
    FOREIGN KEY (owner) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (room) REFERENCES room(id) ON DELETE CASCADE
);
